"""Add image_url to Room

Revision ID: 42ccd16a6bc2
Revises: 5b11b7352db4
Create Date: 2025-12-02 18:36:12.275803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ccd16a6bc2'
down_revision = '5b11b7352db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
